# Generated by Django 4.1.4 on 2022-12-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='email',
            field=models.CharField(default='2', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='facebook',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='linkedin',
            field=models.CharField(max_length=150),
        ),
    ]
