# Generated by Django 4.1.4 on 2022-12-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sociallinks_email_alter_sociallinks_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webimage', models.ImageField(default='', upload_to='website/images')),
                ('weblogo', models.ImageField(default='', upload_to='website/images')),
                ('webintro', models.TextField(default='', max_length=1000)),
                ('aboutus', models.TextField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
