# Generated by Django 4.1.4 on 2022-12-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardimage', models.ImageField(upload_to='website/images')),
                ('cardname', models.CharField(max_length=26)),
                ('description', models.TextField(max_length=1600)),
            ],
        ),
    ]
